import type { User } from '@prisma/client';
import type {
  PublicUserDto,
  SelfUserDto,
  Gender,
  PreferredSide,
  DominantHand,
  PlayStyle,
  PlayFrequency,
  PlayerGoal,
  UserRole,
  GenderFilter,
  ProfileVisibility,
} from '@padel/shared';

export const toPublicUser = (u: User): PublicUserDto => ({
  id: u.id,
  username: u.username,
  avatarUrl: u.avatarUrl,
  firstName: u.firstName,
  lastName: u.lastName,
  city: u.city,
  bio: u.bio,
  gender: u.gender as Gender,
  padelLevel: u.padelLevel,
  preferredSide: u.preferredSide as PreferredSide,
  dominantHand: u.dominantHand as DominantHand,
  playStyle: u.playStyle as PlayStyle | null,
  playFrequency: u.playFrequency as PlayFrequency,
  goal: u.goal as PlayerGoal,
  glickoRating: u.glickoRating,
  isCoach: u.isCoach,
  role: u.role as UserRole,
  profileVisibility: u.profileVisibility as ProfileVisibility,
  createdAt: u.createdAt.toISOString(),
});

export const toSelfUser = (u: User): SelfUserDto => ({
  ...toPublicUser(u),
  email: u.email,
  phone: u.phone,
  dateOfBirth: u.dateOfBirth.toISOString(),
  prefMaxLevelDiff: u.prefMaxLevelDiff,
  prefGenderFilter: u.prefGenderFilter as GenderFilter,
  prefAgeMin: u.prefAgeMin,
  prefAgeMax: u.prefAgeMax,
  prefRequireGoalMatch: u.prefRequireGoalMatch,
  notifyByEmail: u.notifyByEmail,
  notifyInApp: u.notifyInApp,
  isVerified: u.isVerified,
  emailVerifiedAt: u.emailVerifiedAt?.toISOString() ?? null,
  glickoRD: u.glickoRD,
  glickoVolatility: u.glickoVolatility,
});
